---@class InterpolationModule
local Interpolation = {}

Interpolation.type = {
    linear = 1,
    catmullrom = 2,
    bezier = 3
}

--- Pre-calculates the coefficients for a Catmull-Rom spline segment.
--- @param p0 number The value of the control point before the segment starts.
--- @param p1 number The value at the start of the segment.
--- @param p2 number The value at the end of the segment.
--- @param p3 number The value of the control point after the segment ends.
--- @return table result A table of coefficients {a, b, c, d} for the polynomial equation.
function Interpolation.catmullromCoefficients(p0, p1, p2, p3)
    return {
        a = (-p0 + 3 * p1 - 3 * p2 + p3) * 0.5,
        b = (2 * p0 - 5 * p1 + 4 * p2 - p3) * 0.5,
        c = (-p0 + p2) * 0.5,
        d = p1
    }
end

--- Evaluates the Catmull-Rom spline at a specific time 't' using pre-calculated coefficients.
--- @param coeff table The coefficient table generated by `catmullromCoefficients`.
--- @param t number The normalized time (0 to 1) within the segment.
--- @return number result The interpolated value at time 't'.
function Interpolation.catmullromEval(coeff, t)
    return ((coeff.a * t + coeff.b) * t + coeff.c) * t + coeff.d
end

--- Calculates a point on a standard cubic Bézier curve.
--- @param t number The normalized time (0 to 1) along the curve.
--- @param p0 number The starting point's value.
--- @param p1 number The first control point's value (handle of the start point).
--- @param p2 number The second control point's value (handle of the end point).
--- @param p3 number The ending point's value.
--- @return number result The interpolated value at time 't'.
function Interpolation.cubicBezier(t, p0, p1, p2, p3)
    local u = 1 - t
    local tt = t * t
    local uu = u * u
    local uuu = uu * u
    local ttt = tt * t
    
    return uuu * p0 + 3 * uu * t * p1 + 3 * u * tt * p2 + ttt * p3
end

return Interpolation